version: "3.4"
name: "neo"

networks:
  nginx-php-mysql:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: neo.nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/neo
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-php-mysql

  php:
    container_name: neo.php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/neo
    networks:
      - nginx-php-mysql

  mysql:
    image: mysql:8
    container_name: neo.mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_PASSWORD: Passw0rd
    networks:
      - nginx-php-mysql